name: NovaSpleef
main: net.novauniverse.games.spleef.NovaSpleef
description: Novauniverse Spleef
version: 1.0
depend: [NovaCore, NovaCoreGameEngine]
softdepend: [NovaGamesTarget]

authors: [Zeeraa, NovaUniverse]